name: Maven Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true
        type: string
      java:
        description: "Java version"
        required: true
        type: string
        default: '8'        
jobs:
  maven-release:
    uses: RegioneER/parer-github-template/.github/workflows/release.yml@main
    with:
      version: ${{ inputs.version }}
  